### ISSUE TITLE
Bug introduced due to CVE-2022-24767 fix

### ISSUE THREAD

**Issue by lawndoc** [DariuszPorowski/github-action-gitleaks#39]
This action is creating the following error when running this workflow in GitHub due to using a new version of git:

```
gitleaks detect --config /.gitleaks/GitleaksUdmCombo.toml --report-format json --redact --verbose --log-level info --report-path /github/workspace/gitleaks-report.json --source /github/workspace

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

3:11PM ERR fatal: unsafe repository ('/github/workspace' is owned by someone else)
3:11PM ERR To add an exception for this directory, call:
3:11PM ERR 
3:11PM ERR 	git config --global --add safe.directory /github/workspace
```

**To Reproduce**

Run the below workflow on any repo:
```yaml
name: GitLeaks Secret Scan

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:
    branches:
      - $default-branch

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Update Secret Definitions # from the GitLeaks main repository
        run: mkdir security && wget -P security/ https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml

      - name: Run GitLeaks Scan
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          config-path: security/gitleaks.toml
```

**Additional context**
This issue appears to be a result of the fix for CVE-2022-24767 in git
