### ISSUE TITLE
Action not working in Pull Request

### ISSUE THREAD

**Issue by lawndoc** [DariuszPorowski/github-action-gitleaks#41]
When using the Action in a pull request workflow, the action fails with a generic Git error:

![image](https://user-images.githubusercontent.com/24688343/170765442-9d11b794-884a-473b-8f53-512c34e4f2cc.png)

**To Reproduce**

Set up the following workflow, create a different branch, and open a pull request that kicks off the workflow:

```yaml
name: GitLeaks Secret Scan

# It's recommended to leave the triggers like this
# to reduce workflows running on all branches. To
# catch commited secrets sooner, please install a
# pre-commit hook as shown at:
# https://github.com/zricethezav/gitleaks#pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    
    - name: Update Secret Definitions  # from the GitLeaks main repository
      run: mkdir security && wget -P security/ https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml

    - name: Run GitLeaks Scan
      id: gitleaks
      uses: DariuszPorowski/github-action-gitleaks@v2
      with:
        config-path: security/gitleaks.toml
```

**Ideas on root cause**
Based on the error indicating that the git ref doesn't exist, this may be caused by the workflow not fetching the main branch during the pull request automation. I'll have to perform more testing to know know for sure.
