### ISSUE TITLE
Error on fetch-depth > 0

### ISSUE THREAD

**Issue by lucas-dantas-isaac** [DariuszPorowski/github-action-gitleaks#51]
**Describe the bug**
Error on fetch-depth: '5'

```
5:25PM DBG using gitleaks config /.gitleaks/GitleaksUdmCombo.toml from `--config`
5:25PM DBG executing: /usr/bin/git -C /github/workspace log -p -U0 refs/remotes/origin/main^..cc6174683f[81](https://github.com/OlaIsaac/badrepo/runs/7863601254?check_suite_focus=true#step:4:84)0199398f6eff6f01c0778b9aaa39
5:25PM ERR fatal: ambiguous argument 'refs/remotes/origin/main^..cc6174683f810199398f6eff6f01c0778b9aaa39': unknown revision or path not in the working tree.
5:25PM ERR Use '--' to separate paths from revisions, like this:
5:25PM ERR 'git <command> [<revision>...] -- [<file>...]'
----------------------------------

Error: STOP! Gitleaks encountered leaks or error
```

**To Reproduce**

1. 'Set  fetch-depth '
```

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
        fetch-depth: '5'
    - name: Run Gitleaks
       id: gitleaks
       uses: DariuszPorowski/github-action-gitleaks@v2
```
