### ISSUE TITLE
fatal: detected dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by takashiuesaka** [DariuszPorowski/github-action-gitleaks#53]
**Describe the bug**

When I used the github-action-gitleaks@v2 with source arg, the error occurred.

**To Reproduce**

1. Use this actions with source env.

```yaml
      - name: "Check for secrets with Gitleaks"
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          source: apis/poi
          config: gitleaksconfig.toml
          report_format: "sarif"
          fail: false
```

2. error occurred

```
2:08AM ERR [git] fatal: detected dubious ownership in repository at '/github/workspace'
2:08AM ERR [git] To add an exception for this directory, call:
2:08AM ERR [git] 
2:08AM ERR [git] 	git config --global --add safe.directory /github/workspace
2:08AM ERR git error encountered, see logs
2:08AM WRN partial scan completed in 58.798585ms
2:08AM WRN no leaks found in partial scan
```

**Expected behavior**

do not cause error when source arg is set

**Screenshots**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/61622933/186057479-94e3a29f-f3d2-4a1e-a46d-d9dca52fe10f.png">

**Additional context**

This reason of this error is CVE-2022-24765. And I know that the code to fix CVE-2022-24765 is already implements in entrypoint.sh, line 59.

```shell:entrypoint.sh
git config --global --add safe.directory "${INPUT_SOURCE}"
```

But from the error message, it appears that this implementation needs to be changed as follows.

```shell
git config --global --add safe.directory /github/workspace
```
